version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: /bin/bash /startup.sh
    # volumes:
    #   - .:/usr/src/app
    ports:
      - "4444:80"
    depends_on:
      - db
